name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['6.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs

    - name: Check mongo
      run: |
        COUNTER=0
        while !(nc -z localhost 27017) && [[ $COUNTER -lt 60 ]] ; do
          sleep 2
          let COUNTER+=2
          echo "Waiting for mongo to initialize... ($COUNTER seconds so far)"
        done
        sleep 10
        docker logs mongodb
        curl -v localhost:27017
